// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwGdqiDjI_7xM3kH-TMfx6qRLSCp7JsgA',
    appId: '1:1033124259564:web:a98815a0e050d6a6f667c9',
    messagingSenderId: '1033124259564',
    projectId: 'uber-app-998ae',
    authDomain: 'uber-app-998ae.firebaseapp.com',
    storageBucket: 'uber-app-998ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAHCAAJEqZVxlxfzffmdDSbct_EHO5rtc',
    appId: '1:1033124259564:android:dbb9823fe6bd8a14f667c9',
    messagingSenderId: '1033124259564',
    projectId: 'uber-app-998ae',
    storageBucket: 'uber-app-998ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV2VooJ2t75-g4DT2rCXr3AIPoLqH190s',
    appId: '1:1033124259564:ios:1397798e089c02d4f667c9',
    messagingSenderId: '1033124259564',
    projectId: 'uber-app-998ae',
    storageBucket: 'uber-app-998ae.appspot.com',
    iosBundleId: 'com.example.uberUsersApp',
  );
}
